swagger: "2.0"
info:
  title: Versammlungs-API
  description: Beispiel-API zur Verwaltung von Versammlungen in Deutschland für eine fiktive Versammlungsbehörde
  version: 1.0.0
host: localhost
basePath: /v1
schemes:
  - http
paths:
  /versammlung:
    get:
      tags:
        - Versammlung
      summary: Antwortet mit allen Versammlungen nach Tag
      description: Je nach Tag (offen, inBearbeitung, abgestimmt, abgesagt)
      produces:
        - application/json
      responses:
        200:
          description: OK
    post:
      tags:
        - Versammlung
      summary: Anlegen einer neuen Versammlung
      description: Erlaubt einem Bürger das Anlegen einer Versammlung
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Anzulegende Versammlung
          required: true
          schema:
            allOf:
              - $ref: '#/definitions/Versammlung'
              - required:
                  - vorname
                  - nachname
                  - motto
                  - start
                  - ende
                  - route
                  - kontakt
                  - teilnehmer
                  - hilfsmittel
      responses:
        200:
          description: OK
        400:
          description: Fehlerhafte Anfrage
        500:
          description: Interner Fehler
  /versammlung/{uuid}:
    get:
      tags:
        - Versammlung
      summary: Antwortet mit einer spezifischen Versammlung
      description: Je nach angegebener UUID kann eine Versammlung direkt adressiert und abegfragt werden.
      produces:
        - application/json
      parameters:
        - name: "uuid"
          in: "path"
          description: "UUID der Versammlung"
          required: true
          type: "string"
      responses:
        200:
          description: OK
        404:
          description: Unbekannte UUID
        500:
          description: Interner Fehler
    put:
      tags:
        - Versammlung
      summary: Bearbeiten einer spezifischen Versammlung
      description: Erlaubt das Abändern von Versammlungen.
      produces:
        - application/json
      parameters:
        - name: "uuid"
          in: "path"
          description: "UUID der Versammlung"
          required: true
          type: "string"
        - in: body
          name: body
          description: Anzulegende Versammlung
          required: true
          schema:
            allOf:
              - $ref: '#/definitions/Versammlung'
      responses:
        200:
          description: OK
        400:
          description: Fehlerhafte Anfrage
        404:
          description: Unbekannte UUID
        500:
          description: Interner Fehler
definitions:
  Versammlung:
    type: object
    properties:
      vorname:
        type: string
        example: Philipp
      nachname:
        type: string
        example: Bolte
      motto:
        type: string
        example: 'Fuer den Sommer!'
      start:
        type: string
        example: '30.07.2020 13:00'
      ende:
        type: string
        example: '30.07.2020 18:00'
      route:
        type: string
        example: 'Campus der TH-Brandenburg'
      kontakt:
        type: string
        example: '0173 88886321'
      teilnehmer:
        type: integer
        example: '100'
      hilfsmittel:
        type: string
        example: 'Lautsprecherwagen, ...'
    xml:
      name: Users
externalDocs:
  description: GitHub Repository der API
  url: 'https://github.com/strumswell/e-filing-protest-mako'